server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data-transaksi?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: base
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: nentinur300901@gmail.com
    password: wrylziivnvyxyacr
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 30000
          timeout: 30000
    protocol: smtp
    test-connection: false

    spring:
      datasource:
        url: jdbc:postgresql://localhost:5432/data-transaksi
        username: nentinur
        password: Nn300901
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
      config:
        activate:
          on-profile: dev
      messages:
        basename: base
      mail:
        default-encoding: UTF-8
        host: smtp.gmail.com
        username: nentinur300901@gmail.com
        password: wrylziivnvyxyacr
        port: 587
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
                required: true
              connection-timeout: 30000
              timeout: 30000
              protocol: smtp
              test-connection: false