server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  datasource:
    url: jdbc:mysql://localhost:3306/transaksi?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    activate:
      on-profile: dev
  messages:
    basename: base
  mail:
  default-encoding: UTF-8
  host: smtp.gmail.com
  username: nenur2001@gmail.com
  password: kwtxitplrerypjqq
  port: 587
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 30000
        timeout: 30000
  protocol: smtp
  test-connection: false